config/routes.rb
Rails.application.routes.draw do
  	root 'homes#top'
	devise_for :users, controllers: {
	  sessions: 'users/sessions',
	  registrations: 'users/registrations'
	}
	resources :homes, only:[:new,:create]
	resources :users
	resources :tweets do
		resource :comments, only: [:create, :destroy]
    	resource :favorites, only: [:create, :destroy]
    end
    resources :messages, :only => [:create]
    resources :rooms, :only => [:create, :show, :index]
    post 'follow/:id' => 'relationships#follow', as: 'follow'
    post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
	get 'users/following/:user_id' => 'users#following', as:'users_following'
	get 'users/follower/:user_id' => 'users#follower', as:'users_follower'
    get 'search' => 'users#search'
    get 'favorite/:user_id' => 'favorites#index',as:'favorite'
end

app/models/user.rb
class User < ApplicationRecord
	devise :database_authenticatable, :registerable,
	:recoverable, :rememberable, :validatable

	validates :name, presence: true, uniqueness: true, length: { in: 1..20 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
	validates :password, presence: true, length: { in: 8..20 },on: :sign_up
	validates :introduction, length: { maximum: 100 }

	attachment :profile_image
	attachment :header_image

	has_many :tweets, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	has_many :favorite_tweets, through: :favorites, source: :tweet
	has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
	has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
	has_many :following_user, through: :follower, source: :followed
	has_many :follower_user, through: :followed, source: :follower
	has_many :messages, dependent: :destroy
	has_many :entries, dependent: :destroy

	def update_without_current_password(params, *options)
		params.delete(:current_password)

		if params[:password].blank? && params[:password_confirmation].blank?

			params.delete(:password)
			params.delete(:password_confirmation)
		end

		result = update_attributes(params, *options)
		clean_up_passwords
		result
	end

	def follow(user_id)
		follower.create(followed_id: user_id)
	end

	def unfollow(user_id)
		follower.find_by(followed_id: user_id).destroy
	end

	def following?(user)
		following_user.include?(user)
	end

	def User.search(search, user_or_tweet)
	    if user_or_tweet == "1"
	       User.where(['name LIKE ?', "%#{search}%"])
	    else
	       User.all
	    end
	end

    def favorited_by?(tweet_id)
      favorites.where(tweet_id: tweet_id).exists?
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
		@tweets = @user.tweets
	    @currentUserEntry=Entry.where(user_id: current_user.id)
	    @userEntry=Entry.where(user_id: @user.id)
	    if @user.id == current_user.id
	    else
	      @currentUserEntry.each do |cu|
	        @userEntry.each do |u|
	          if cu.room_id == u.room_id then
	            @isRoom = true
	            @roomId = cu.room_id
	          end
	        end
	      end
	      if @isRoom
	      else
	        @room = Room.new
	        @entry = Entry.new
	      end
	    end
	end

	def following
		@user = User.find(params[:user_id])
	end

	def follower
		@user = User.find(params[:user_id])
	end

	def search
		@user_or_tweet = params[:option]
	if @user_or_tweet == "1"
	  	@users = User.search(params[:search], @user_or_tweet)
	else
	  	@tweets = Tweet.search(params[:search], @user_or_tweet)
	end
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/follower.html.erb
<div class="container">
    <div class="row">
        <div class="tweets-sidebar-left col-lg-2">
            <%= render "shared/sidebar-left" %>
        </div>
        <div class="col-lg-7">
            <h3>フォロワー</h3>
            <table class="table">
                <tbody>
                    <% @user.follower_user.where.not(id: current_user.id).each do |user| %>
                        <tr class="user_<%= user.id %>">
                            <%= render "shared/follow", user: user %>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
        <div class="col-lg-3">
            <%= render "shared/sidebar-right" %>
        </div>
    </div>
</div>

app/views/users/following.html.erb
<div class="container">
	<div class="row">
		<div class="tweets-sidebar-left col-lg-2">
			<%= render "shared/sidebar-left" %>
		</div>
		<div class="col-lg-7">
			<h3>フォロー中</h3>
			<table class="table">
				<tbody>
					<% @user.following_user.where.not(id: current_user.id).each do |user| %>
						<tr class="user_<%= user.id %>">
	                		<%= render "shared/follow", user: user %>
	                	</tr>
					<% end %>
				</tbody>
			</table>
		</div>
		<div class="col-lg-3">
			<%= render "shared/sidebar-right" %>
		</div>
	</div>
</div>

app/views/users/search.html.erb
<div class="container">
    <div class="row">
        <div class="tweets-sidebar-left col-lg-2">
            <%= render "shared/sidebar-left" %>
        </div>
        <div class="col-lg-7">
            <h1>検索</h1>
            <%= form_tag(search_path, :method => 'get') do %>
                <%= select_tag(:option, options_for_select([["アカウント", "1"],["ツイート","2"]]))%>
                <%= text_field_tag :search %>
                <%= submit_tag 'Search' %>
            <% end %>
            <% if @user_or_tweet == "1"%>
                <h1>アカウント</h1>
                <table class="table">
                    <% @users.each do |user| %>
                    <thead>
                        <tr>
                            <td>
                                <%= attachment_image_tag user, :profile_image, :size =>'100x100', class: "img-circle pull-left profile-thumb", fallback: "no_image1.jpg" %>
                                <p><%= link_to user.name,user_path(user) %></p>
                                <p><%= user.introduction %></p>
                            </td>
                        </tr>
                    </thead>
                    <% end %>
                </table>
            <% elsif @user_or_tweet == "2" %>
                <h2>ツイート</h2>
                <table class="table">
                <% @tweets.each do |tweet| %>
                    <thead>
                        <tr>
                            <td>
                                <%= attachment_image_tag tweet.user, :profile_image, :size =>'100x100', class: "img-circle pull-left profile-thumb", fallback: "no_image1.jpg" %>
                                <p><%= link_to tweet.user.name,user_path(tweet.user) %></p>
                                <p><%= link_to tweet.body,tweet_path(tweet) %></p>
                            </td>
                        </tr>
                    </thead>
                <% end %>
                </table>
            <% else %>
            <% end %>
            <table class="table">
                <tbody>
                    <tr>
                        <td>

                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-lg-3">
        </div>
    </div>
</div>

app/views/users/show.html.erb
<div class="container">
    <div class="row">
    	<div class="tweets-sidebar-left col-lg-2">
            <%= render "shared/sidebar-left" %>
        </div>
        <div class="col-lg-7">
            <%= attachment_image_tag @user, :header_image, :size =>'680x200', class: "img-rounded", fallback: "no_image2.jpg" %>
            <%= attachment_image_tag @user, :profile_image, :size =>'150x150', class: "img-circle pull-left profile-thumb", fallback: "no_image1.jpg" %>
            <p>
                <% if @user == current_user %>
                    <%= link_to "プロフィールを編集",edit_user_registration_path(@user) %>
                <% end %>
            </p>
            <p><%= @user.name %></p>
            <p><%= @user.introduction %></p>
            <p>誕生日 <%= @user.birthday %></p>
            <%= link_to "#{@user.follower.count} フォロー中",users_following_path(@user) %>
            <%= link_to "#{@user.followed.count} フォロワー",users_follower_path(@user) %>
            <% unless @user == current_user %>
                <% if current_user.following?(@user) %>
                    <div class="user_<%= @user.id %>">
                        <%= link_to 'フォロー解除', unfollow_path(@user.id), method: :POST,class:"btn btn-info", remote: true %>
                    </div>
                <% else %>
                    <div class="user_<%= @user.id %>">
                        <%= link_to 'フォロー', follow_path(@user.id), method: :POST,class:"btn btn-default", remote: true %>
                    </div>
                <% end %>
            <% end %>

            <% if @user.id == current_user.id %>
            <% else %>
              <% if @isRoom == true %>
                <p><a href="/rooms/<%= @roomId %>" class="btn btn-info" >チャットへ</a>
              <% else %>
                <%= form_for @room do |f| %>
                  <%= fields_for @entry do |e| %>
                    <%= e.hidden_field :user_id, :value=> @user.id %>
                  <% end %>
                  <%= f.submit "メッセージ",class:"btn btn-info" %>
                <% end %>
              <% end %>
            <% end %>
            <%= link_to "いいね一覧",favorite_path(@user) %>
            <table class="table">
                <thead>
                    <tr>
                        <th>ツイート</th>
                    </tr>
                </thead>
                <tbody>
                    <% @tweets.each do |tweet| %>
                        <tr class="tweet_<%= tweet.id %>">
                            <td><%= render "shared/tweets", tweet: tweet %></td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
        <div class="col-lg-3">
            <%= render "shared/sidebar-right" %>
        </div>
    </div>
</div>