config/routes.rb
Rails.application.routes.draw do
  	root 'homes#top'
	devise_for :users, controllers: {
	  sessions: 'users/sessions',
	  registrations: 'users/registrations'
	}
	resources :homes, only:[:new,:create]
	resources :users
	resources :tweets do
		resource :comments, only: [:create, :destroy]
    	resource :favorites, only: [:create, :destroy]
    end
    resources :messages, :only => [:create]
    resources :rooms, :only => [:create, :show, :index]
    post 'follow/:id' => 'relationships#follow', as: 'follow'
    post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
	get 'users/following/:user_id' => 'users#following', as:'users_following'
	get 'users/follower/:user_id' => 'users#follower', as:'users_follower'
    get 'search' => 'users#search'
    get 'favorite/:user_id' => 'favorites#index',as:'favorite'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :tweet
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :tweet
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :messages, dependent: :destroy
    has_many :entries, dependent: :destroy
end

app/models/tweet.rb
class Tweet < ApplicationRecord
	validates :body, presence: true, length: { maximum: 140 }

	attachment :tweet_image

  belongs_to :user
  has_many :comments, dependent: :destroy
	has_many :favorites, dependent: :destroy

    def favorited_by?(user)
      favorites.where(user_id: user.id).exists?
    end

    def Tweet.search(search, user_or_tweet)
      if user_or_tweet == "2"
         Tweet.where(['body LIKE ?', "%#{search}%"])
      else
         Tweet.all
      end
    end
end

app/models/user.rb
class User < ApplicationRecord
	devise :database_authenticatable, :registerable,
	:recoverable, :rememberable, :validatable

	validates :name, presence: true, uniqueness: true, length: { in: 1..20 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
	validates :password, presence: true, length: { in: 8..20 },on: :sign_up
	validates :introduction, length: { maximum: 100 }

	attachment :profile_image
	attachment :header_image

	has_many :tweets, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	has_many :favorite_tweets, through: :favorites, source: :tweet
	has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
	has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
	has_many :following_user, through: :follower, source: :followed
	has_many :follower_user, through: :followed, source: :follower
	has_many :messages, dependent: :destroy
	has_many :entries, dependent: :destroy

	def update_without_current_password(params, *options)
		params.delete(:current_password)

		if params[:password].blank? && params[:password_confirmation].blank?

			params.delete(:password)
			params.delete(:password_confirmation)
		end

		result = update_attributes(params, *options)
		clean_up_passwords
		result
	end

	def follow(user_id)
		follower.create(followed_id: user_id)
	end

	def unfollow(user_id)
		follower.find_by(followed_id: user_id).destroy
	end

	def following?(user)
		following_user.include?(user)
	end

	def User.search(search, user_or_tweet)
	    if user_or_tweet == "1"
	       User.where(['name LIKE ?', "%#{search}%"])
	    else
	       User.all
	    end
	end

    def favorited_by?(tweet_id)
      favorites.where(tweet_id: tweet_id).exists?
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

	def top
	    if user_signed_in?
	    	redirect_to tweets_path
	    else
	        root_path
	    end
	end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
	before_action :authenticate_user!
	def create
		@room = Room.create
		@entry1 = Entry.create(:room_id => @room.id, :user_id => current_user.id)
		@entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(:room_id => @room.id))
		redirect_to "/rooms/#{@room.id}"
	end

	def show
		@room = Room.find(params[:id])
		if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
			@messages = @room.messages
			@message = Message.new
			@entries = @room.entries
		else
			redirect_back(fallback_location: root_path)
		end
	end

	def index
	  @currentEntries = current_user.entries
	  myRoomIds = []

	  @currentEntries.each do |entry|
	    myRoomIds << entry.room.id
	  end

	  @anotherEntries = Entry.where(room_id: myRoomIds).where('user_id != ?',current_user.id)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
		@tweets = @user.tweets
	    @currentUserEntry=Entry.where(user_id: current_user.id)
	    @userEntry=Entry.where(user_id: @user.id)
	    if @user.id == current_user.id
	    else
	      @currentUserEntry.each do |cu|
	        @userEntry.each do |u|
	          if cu.room_id == u.room_id then
	            @isRoom = true
	            @roomId = cu.room_id
	          end
	        end
	      end
	      if @isRoom
	      else
	        @room = Room.new
	        @entry = Entry.new
	      end
	    end
	end

	def following
		@user = User.find(params[:user_id])
	end

	def follower
		@user = User.find(params[:user_id])
	end

	def search
		@user_or_tweet = params[:option]
	if @user_or_tweet == "1"
	  	@users = User.search(params[:search], @user_or_tweet)
	else
	  	@tweets = Tweet.search(params[:search], @user_or_tweet)
	end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Twitter</title>
	<%= csrf_meta_tags %>
	<%= csp_meta_tag %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	<script src="https://kit.fontawesome.com/c51513dd6c.js" crossorigin="anonymous"></script>
</head>

<body>
	<% if user_signed_in? %>
	<nav class="navbar navbar-inverse">
		<div class="container-fluid">
			<div class="navbar-header">
				<li><%= link_to "Twitter", root_path, class: "navbar-brand" %></li>
			</div>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to 'タイムライン', tweets_path %></li>
				<li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
			</ul>
		</div>
	</nav>
	<% else %>
	<nav class="navbar navbar-inverse">
		<div class="container-fluid">
			<div class="navbar-header">
				<li><%= link_to "Twitter", root_path, class: "navbar-brand" %></li>
			</div>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "アカウント作成", new_user_registration_path %></li>
				<li><%= link_to "ログイン", new_user_session_path %></li>
			</ul>
		</div>
	</nav>
	<% end %>
	<%= yield %>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
    <div id="error_explanation">
    	<h2>
            <%= I18n.t("errors.messages.not_saved",count: resource.errors.count,resource: resource.class.model_name.human.downcase)%>
    	</h2>
    	<ul>
    		<% resource.errors.full_messages.each do |message| %>
    			<li><%= message %></li>
    		<% end %>
    	</ul>
    </div>
<% end %>

app/views/shared/_follow.html.erb
<td>
    <%= link_to user_path(user) do %>
        <%= attachment_image_tag user, :profile_image, :size =>'30x30', class: "img-circle pull-left profile-thumb", fallback: "no_image1.jpg" %>
        <p><%= user.name %></p>
        <p><%= user.introduction %></p>
    <% end %>
    <% if current_user.following?(user) %>
        <%= link_to 'フォロー解除', unfollow_path(user.id), method: :POST,class:"btn btn-info", remote: true %>
    <% else %>
        <%= link_to 'フォロー', follow_path(user.id), method: :POST,class:"btn btn-default", remote: true %>
    <% end %>
</td>

app/views/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
    <%= link_to "ログイン", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
    <%= link_to "アカウント作成", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
    <%= link_to "パスワードを忘れましたか？", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
    <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
    <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
    <%- resource_class.omniauth_providers.each do |provider| %>
        <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
    <% end %>
<% end %>

app/views/shared/_sidebar-left.html.erb
<p>
	<i class="fab fa-twitter"></i>
</p>
<p>
	<i class="fas fa-home"></i>
	<%= link_to "ホーム",tweets_path %>
</p>
<p>
	<i class="fas fa-hashtag"></i>
	<%= link_to "話題を検索" %>
</p>
<p>
	<i class="fa fa-bell-o"></i>
	<%= link_to "通知" %>
</p>
<p>
	<i class="far fa-envelope"></i>
	<%= link_to "メッセージ",rooms_path %>
</p>
<p>
	<i class="fa fa-bookmark-o"></i>
	<%= link_to "ブックマーク" %>
</p>
<p>
	<i class="far fa-list-alt"></i>
	<%= link_to "リスト" %>
</p>
<p>
	<%= attachment_image_tag current_user, :profile_image, :size =>'30x30', class: "img-circle pull-left profile-thumb", fallback: "no_image1.jpg" %>
	<%= link_to "プロフィール",user_path(current_user) %>
</p>
<p>
	<i class="far fa-comment-dots"></i>
	<%= link_to "もっと見る" %>
</p>
<%= link_to "ツイートする",new_tweet_path,class:"btn btn-info btn-block" %>

app/views/shared/_sidebar-right.html.erb
<p>検索</p>
<%= form_tag(search_path,:method => 'get') do %>
  <%= text_field_tag :search %>
  <%= submit_tag 'Search', :name => nil %>
<% end %>

app/views/shared/_tweets.html.erb
<td>
	<%= attachment_image_tag tweet.user, :profile_image, :size =>'30x30', class: "img-circle pull-left profile-thumb", fallback: "no_image1.jpg" %>
	<%= link_to tweet.user.name,user_path(tweet.user) %>
	<p><%= link_to tweet.body,tweet_path(tweet)%></p>
	<i class="far fa-comment"></i>
    <%= tweet.comments.count %>
	<% if tweet.favorited_by?(current_user) %>
		<%= link_to tweet_favorites_path(tweet), method: :delete, remote: true do %>
		<i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
		<%= tweet.favorites.count %>
		<% end %>
		<% else %>
		<%= link_to tweet_favorites_path(tweet), method: :post, remote: true do %>
		<i class="fa fa-heart-o" aria-hidden="true"></i>
		<%= tweet.favorites.count %>
		<% end %>
	<% end %>
</td>