config/routes.rb
Rails.application.routes.draw do
  	root 'homes#top'
	devise_for :users, controllers: {
	  sessions: 'users/sessions',
	  registrations: 'users/registrations'
	}
	resources :homes, only:[:new,:create]
	resources :users
	resources :tweets do
		resource :comments, only: [:create, :destroy]
    	resource :favorites, only: [:create, :destroy]
    end
    resources :messages, :only => [:create]
    resources :rooms, :only => [:create, :show, :index]
    post 'follow/:id' => 'relationships#follow', as: 'follow'
    post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
	get 'users/following/:user_id' => 'users#following', as:'users_following'
	get 'users/follower/:user_id' => 'users#follower', as:'users_follower'
    get 'search' => 'users#search'
    get 'favorite/:user_id' => 'favorites#index',as:'favorite'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :tweet
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :tweet
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :messages, dependent: :destroy
    has_many :entries, dependent: :destroy
end

app/models/tweet.rb
class Tweet < ApplicationRecord
	validates :body, presence: true, length: { maximum: 140 }

	attachment :tweet_image

  belongs_to :user
  has_many :comments, dependent: :destroy
	has_many :favorites, dependent: :destroy

    def favorited_by?(user)
      favorites.where(user_id: user.id).exists?
    end

    def Tweet.search(search, user_or_tweet)
      if user_or_tweet == "2"
         Tweet.where(['body LIKE ?', "%#{search}%"])
      else
         Tweet.all
      end
    end
end

app/models/user.rb
class User < ApplicationRecord
	devise :database_authenticatable, :registerable,
	:recoverable, :rememberable, :validatable

	validates :name, presence: true, uniqueness: true, length: { in: 1..20 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
	validates :password, presence: true, length: { in: 8..20 },on: :sign_up
	validates :introduction, length: { maximum: 100 }

	attachment :profile_image
	attachment :header_image

	has_many :tweets, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	has_many :favorite_tweets, through: :favorites, source: :tweet
	has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
	has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
	has_many :following_user, through: :follower, source: :followed
	has_many :follower_user, through: :followed, source: :follower
	has_many :messages, dependent: :destroy
	has_many :entries, dependent: :destroy

	def update_without_current_password(params, *options)
		params.delete(:current_password)

		if params[:password].blank? && params[:password_confirmation].blank?

			params.delete(:password)
			params.delete(:password_confirmation)
		end

		result = update_attributes(params, *options)
		clean_up_passwords
		result
	end

	def follow(user_id)
		follower.create(followed_id: user_id)
	end

	def unfollow(user_id)
		follower.find_by(followed_id: user_id).destroy
	end

	def following?(user)
		following_user.include?(user)
	end

	def User.search(search, user_or_tweet)
	    if user_or_tweet == "1"
	       User.where(['name LIKE ?', "%#{search}%"])
	    else
	       User.all
	    end
	end

    def favorited_by?(tweet_id)
      favorites.where(tweet_id: tweet_id).exists?
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        tweet = Tweet.find(params[:tweet_id])
        comment = Comment.new(comment_params)
        comment.user_id = current_user.id
        comment.tweet_id = tweet.id
        comment.save
        redirect_to tweet_path(tweet)
    end

    private
    def comment_params
        params.require(:comment).permit(:body)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

	def top
	    if user_signed_in?
	    	redirect_to tweets_path
	    else
	        root_path
	    end
	end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
	before_action :authenticate_user!
	def create
		@room = Room.create
		@entry1 = Entry.create(:room_id => @room.id, :user_id => current_user.id)
		@entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(:room_id => @room.id))
		redirect_to "/rooms/#{@room.id}"
	end

	def show
		@room = Room.find(params[:id])
		if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
			@messages = @room.messages
			@message = Message.new
			@entries = @room.entries
		else
			redirect_back(fallback_location: root_path)
		end
	end

	def index
	  @currentEntries = current_user.entries
	  myRoomIds = []

	  @currentEntries.each do |entry|
	    myRoomIds << entry.room.id
	  end

	  @anotherEntries = Entry.where(room_id: myRoomIds).where('user_id != ?',current_user.id)
	end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
	def new
		@tweet = Tweet.new
	end

	def create
		@tweet = Tweet.new(tweet_params)
		@tweet.user_id = current_user.id
		@tweet.save
	end

	def index
		@tweet = Tweet.new
		@tweets = Tweet.all.order(id: "DESC")
	end

	def show
		@tweet = Tweet.find(params[:id])
		@comments = @tweet.comments.order(id: "DESC")
		@comment = Comment.new
	end

	def destroy
		if user_signed_in?
			tweet = Tweet.find(params[:id])
			tweet.destroy
			redirect_to tweets_path
		end
	end

	private

	def tweet_params
		params.require(:tweet).permit(:title,:body,:tweet_image)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
		@tweets = @user.tweets
	    @currentUserEntry=Entry.where(user_id: current_user.id)
	    @userEntry=Entry.where(user_id: @user.id)
	    if @user.id == current_user.id
	    else
	      @currentUserEntry.each do |cu|
	        @userEntry.each do |u|
	          if cu.room_id == u.room_id then
	            @isRoom = true
	            @roomId = cu.room_id
	          end
	        end
	      end
	      if @isRoom
	      else
	        @room = Room.new
	        @entry = Entry.new
	      end
	    end
	end

	def following
		@user = User.find(params[:user_id])
	end

	def follower
		@user = User.find(params[:user_id])
	end

	def search
		@user_or_tweet = params[:option]
	if @user_or_tweet == "1"
	  	@users = User.search(params[:search], @user_or_tweet)
	else
	  	@tweets = Tweet.search(params[:search], @user_or_tweet)
	end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.js.erb
$("textarea").val("");
$(".new").before('<tr id="tweet_<%= @tweet.id %>"></tr>');
$(".tweet_<%= @tweet.id %>").html("<%= j(render 'shared/tweets', tweet: @tweet ) %>");

app/views/rooms/index.html.erb
<div class="container">
    <div class="row">
        <div class="tweets-sidebar-left col-lg-2">
            <%= render "shared/sidebar-left" %>
        </div>
        <div class="col-lg-3">
            <table class="table">
                <tbody>
                    <h1>メッセージ</h1>
                    <% @anotherEntries.each do |e| %>
                    <tr>
                        <td>
                            <%= link_to room_path(e.room.id) do %>
                            <%= attachment_image_tag e.user, :profile_image, :size =>'30x30', class: "img-circle pull-left profile-thumb", fallback: "no_image1.jpg" %>
                            <%= e.user.name %>
                            <p><%= Message.find_by(id: e.room.message_ids.last).content %></p>
                            <% end %>
                        </td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
        <div class="col-lg-7">
        </div>
    </div>
</div>

app/views/rooms/show.html.erb
<div class="container">
    <div class="row">
        <div class="tweets-sidebar-left col-lg-2">
            <%= render "shared/sidebar-left" %>
        </div>
        <div class="col-lg-7">
            <h1>DM</h1>

            <h4>参加者</h4>
            <% @entries.each do |e| %>
            <h5><strong><a href="/users/<%= e.user.id %>"><%= e.user.name %></a></strong></h5>
            <% end %>

            <hr>
            <% if @messages.present? %>
            <% @messages.each do |m| %>
            <strong><%= m.content %></strong>
            <%= attachment_image_tag m.user, :profile_image, :size =>'30x30', class: "img-circle pull-left profile-thumb", fallback: "no_image1.jpg" %>
            <small><strong><a href="/users/<%= m.user_id %>"><%= m.user.name %></a></strong></small>
            <hr>
            <% end %>
            <% else %>
            <h3 class="text-center">メッセージはまだありません</h3>
            <% end %>

            <%= form_for @message do |f| %>
            <%= f.text_field :content, :placeholder => "メッセージを入力して下さい" , :size => 70 %>
            <%= f.hidden_field :room_id, :value => @room.id %>
            <br>
            <%= f.submit "送信",class:"btn btn-info" %>
            <% end %>
        </div>
        <div class="col-lg-3">
            <%= render "shared/sidebar-right" %>
        </div>
    </div>
</div>

app/views/tweets/create.js.erb
$("textarea").val("");
$(".new").before('<tr id="tweet_<%= @tweet.id %>"></tr>');
$(".tweet_<%= @tweet.id %>").html("<%= j(render 'shared/tweets', tweet: @tweet ) %>");

app/views/tweets/index.html.erb
<div class="container">
    <div class="row">
        <div class="tweets-sidebar-left col-lg-2">
            <%= render "shared/sidebar-left" %>
        </div>
        <div class="col-lg-7">
            <h1>ホーム</h1>
            <%= form_with(model: Tweet, url: tweets_path, method: :POST, remote: true) do |f| %>
            <%= f.text_area :body %>
            <%= f.submit "ツイートする",class:"btn btn-info" %>
            <% end %>
            <table class="table">
                <tbody>
                    <tr class="new"></tr>
                    <% @tweets.each do |tweet| %>
                    <tr class="tweet_<%= tweet.id %>">
                        <%= render "shared/tweets", tweet: tweet %>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
        <div class="col-lg-3">
            <%= render "shared/sidebar-right" %>
        </div>
    </div>
</div>

app/views/tweets/show.html.erb
<div class="container">
    <div class="row">
        <div class="tweets-sidebar-left col-lg-2">
            <%= render "shared/sidebar-left" %>
        </div>
        <div class="col-lg-7">
            <div class="tweet_<%= @tweet.id %>">
                <p><%= attachment_image_tag @tweet.user, :profile_image, :size =>'100x100', class: "img-circle pull-left profile-thumb", fallback: "no_image1.jpg" %></p>
                <p><%= link_to @tweet.user.name,user_path(@tweet.user) %></p>
                <p><%= @tweet.body %></p>
                <p><%= @tweet.created_at.strftime("%Y-%m-%d %H:%M:%S") %></p>
                <i class="far fa-comment"></i>
                <%= @tweet.comments.count %>
                <% if @tweet.favorited_by?(current_user) %>
                    <%= link_to tweet_favorites_path(@tweet), method: :delete, remote: true do %>
                    <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
                    <%= @tweet.favorites.count %>
                    <% end %>
                    <% else %>
                    <%= link_to tweet_favorites_path(@tweet), method: :post, remote: true do %>
                    <i class="fa fa-heart-o" aria-hidden="true"></i>
                    <%= @tweet.favorites.count %>
                    <% end %>
                <% end %>
                <% if @tweet.user == current_user %>
                <%= link_to "", tweet_path(@tweet), method: :delete,class:"fas fa-trash-alt" %>
                <% end %>
                <%= form_for [@tweet, @comment], remote: true do |f| %>
                <%= f.text_area :body %>
                <%= f.submit "コメントする",class:"btn btn-info" %>
                <% end %>
                <table class="table">
                    <thead>
                        <tr>
                            <th>コメント</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @comments.each do |comment| %>
                            <tr class="new">
                                <td>
                                    <%= attachment_image_tag comment.user, :profile_image, :size =>'30x30', class: "img-circle pull-left profile-thumb", fallback: "no_image1.jpg" %>
	                                <%= link_to comment.user.name,user_path(comment.user) %>
	                                <p><%= link_to comment.body,tweet_path(comment)%></p>
                                </td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-lg-3">
            <%= render "shared/sidebar-right" %>
        </div>
    </div>
</div>